var target = "n00dles";
var moneyThresh = getServerMaxMoney(target) * 0.75;
var securityThresh = getServerMinSecurityLevel(target) + 5;

if (fileExists("BruteSSH.exe", "home")) {
	brutessh(target);
}

if (!hasRootAccess(target)) {
	nuke(target);
}

while (true) {
	if (getServerSecurityLevel(target) > securityThresh) {
		weaken(target);
	} else if (getServerMoneyAvailable(target) < moneyThresh) {
		grow(target);
	} else {
		hack(target);
	}
}
